apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: telegraf
resources:
  - deployment.yaml
  - namespace.yaml
configMapGenerator:
  - name: telegraf
    files:
      - telegraf.conf
secretGenerator:
  - name: telegraf-plugins
    files:
      - telegraf.d/vsphere.conf
      - telegraf.d/wavefront.conf
